- name: Initialize Kubernetes master
  ansible.builtin.shell: |
    kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Set up kubeconfig for root user
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    owner: root
    group: root
    mode: '0600'

- name: Install Calico CNI
  ansible.builtin.shell: |
    set -o pipefail
    kubectl get pods -n kube-system | grep calico || kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
  args:
    executable: /bin/bash
    creates: /etc/cni/net.d/calico-kubeconfig

- name: Generate Kubernetes join command
  ansible.builtin.shell: |
    kubeadm token create --print-join-command > /tmp/kubeadm_join_command.sh
  args:
    creates: /tmp/kubeadm_join_command.sh

- name: Fetch join command from master
  ansible.builtin.fetch:
    src: /tmp/kubeadm_join_command.sh
    dest: ./kubeadm_join_command.sh
    flat: true
